services:
  # Основное приложение (Laravel)
  app:
    build: .
    container_name: arm-app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - .:/var/www
    depends_on:
      - postgres
      - redis
    networks:
      - arm

  # Веб-сервер
  nginx:
    image: nginx:stable-alpine
    container_name: arm-nginx
    ports:
      - "8080:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - arm

  # База данных (Пользователи, Опросы, Игры)
  postgres:
    image: postgres:15-alpine
    container_name: arm-postgres
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: neo
      POSTGRES_PASSWORD: jag-ger-naut-19-88
    networks:
      - arm

  # Аналитическая БД (Логи, Статистика обучения)
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: arm-clickhouse
    ports:
      - "8123:8123"
    networks:
      - arm

  # Хранилище документов (S3)
  minio:
    image: minio/minio:latest
    container_name: arm-minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Консоль управления
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: jag-ger-naut-19-88
      MINIO_SERVER_URL: "http://minio:9000"
      MINIO_BROWSER_REDIRECT_URL: "http://localhost:9001"
      MINIO_API_CORS_ALLOW_ORIGIN: "http://localhost:8080,http://minio:8080"
    command: server /data --console-address ":9001"
    networks:
      - arm

  # Быстрый поиск
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: arm-search
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=masterKey123
    networks:
      - arm

  # Кэш и Очереди (важно для Игр и ИИ)
  redis:
    image: redis:alpine
    container_name: arm-redis
    networks:
      - arm

networks:
  arm:
    driver: bridge
